server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carmarketanalysis
    username: user
    password: password
  flyway:
    enabled: true
  codec:
    max-in-memory-size: 20MB
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE

