server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carmarketanalysis
    username: user
    password: password
  flyway:
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE

